# Generated by Django 3.1.1 on 2021-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20210129_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgss',
            field=models.ImageField(blank=True, null=True, upload_to='new_img/'),
        ),
    ]
