# Generated by Django 3.1.1 on 2021-01-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_remove_post_imgss'),
    ]

    operations = [
        migrations.CreateModel(
            name='post123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='post_post/img1/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_post/')),
            ],
        ),
    ]
